import fs from "node:fs";
import path from "node:path";
import { appendUniqueLines, pathExists, readTextIfExists, writeTextFile } from "./fs-utils.js";

const ENV_GITIGNORE_LINES = [
  "# VibeGuard local secrets",
  ".env",
  ".env.*",
  "!.env.example",
  ".env.vibeguard.local"
];

export function applyFixes(projectRoot, report) {
  const applied = [];

  if (ensureEnvGitignore(projectRoot)) {
    applied.push("Updated .gitignore env protection rules.");
  }

  const secretFindings = report.findings.filter((finding) => finding.fix?.type === "secret-env");
  if (secretFindings.length > 0) {
    const result = quarantineSecrets(projectRoot, secretFindings);
    applied.push(...result);
  }

  const envNames = [
    ...secretFindings.map((finding) => finding.fix.envName),
    ...collectLocalEnvNames(projectRoot)
  ];
  if (ensureEnvExample(projectRoot, envNames)) {
    applied.push("Updated .env.example with required variable names.");
  }

  return applied;
}

function collectLocalEnvNames(projectRoot) {
  const names = new Set();
  for (const entry of fs.readdirSync(projectRoot)) {
    if (entry === ".env.example") continue;
    if (entry !== ".env" && !entry.startsWith(".env.")) continue;

    const content = readTextIfExists(path.join(projectRoot, entry));
    for (const name of parseEnvNames(content)) names.add(name);
  }
  return [...names];
}

export function ensureEnvGitignore(projectRoot) {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  return appendUniqueLines(gitignorePath, ENV_GITIGNORE_LINES);
}

export function ensureEnvExample(projectRoot, envNames) {
  const uniqueNames = [...new Set(envNames.filter(Boolean))].sort();
  if (uniqueNames.length === 0) {
    const envFiles = fs.readdirSync(projectRoot).filter((name) => name === ".env" || name.startsWith(".env."));
    if (envFiles.length === 0 || pathExists(path.join(projectRoot, ".env.example"))) return false;
  }

  const examplePath = path.join(projectRoot, ".env.example");
  const existing = readTextIfExists(examplePath);
  const existingKeys = new Set(
    existing
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => line.split("=")[0].trim())
  );

  const missing = uniqueNames.filter((name) => !existingKeys.has(name));
  if (missing.length === 0 && pathExists(examplePath)) return false;

  const lines = [];
  if (!existing) lines.push("# Values intentionally omitted. Fill these locally or in your deployment secret store.");
  for (const name of missing) lines.push(`${name}=`);

  const next = existing + (existing && !existing.endsWith("\n") ? "\n" : "") + lines.join("\n") + "\n";
  writeTextFile(examplePath, next);
  return true;
}

function quarantineSecrets(projectRoot, findings) {
  const byFile = new Map();
  for (const finding of findings) {
    if (!finding.file || !finding.fix) continue;
    const absolute = path.join(projectRoot, finding.file);
    if (!byFile.has(absolute)) byFile.set(absolute, []);
    byFile.get(absolute).push(finding);
  }

  const envPath = path.join(projectRoot, ".env.vibeguard.local");
  const envContent = readTextIfExists(envPath);
  const usedEnvNames = parseEnvNames(envContent);
  const secretToEnv = new Map();
  const envLines = [];
  const changedFiles = [];

  for (const [filePath, fileFindings] of byFile.entries()) {
    let content = readTextIfExists(filePath);
    if (!content) continue;

    const replacements = [];
    for (const finding of fileFindings) {
      const { start, end, envName, language } = finding.fix;
      const quoted = content.slice(start, end);
      const value = unquote(quoted);
      if (!value) continue;

      const stableKey = `${envName}:${value}`;
      let finalEnvName = secretToEnv.get(stableKey);
      if (!finalEnvName) {
        finalEnvName = nextAvailableEnvName(envName, usedEnvNames);
        usedEnvNames.add(finalEnvName);
        secretToEnv.set(stableKey, finalEnvName);
        envLines.push(`${finalEnvName}=${formatEnvValue(value)}`);
      }

      replacements.push({
        start,
        end,
        replacement: replacementFor(language, finalEnvName)
      });
    }

    if (replacements.length === 0) continue;

    replacements.sort((a, b) => b.start - a.start);
    for (const replacement of replacements) {
      content = content.slice(0, replacement.start) + replacement.replacement + content.slice(replacement.end);
    }

    if (fileFindings.some((finding) => finding.fix.language === "python")) {
      content = ensurePythonOsImport(content);
    }

    writeTextFile(filePath, content);
    changedFiles.push(path.relative(projectRoot, filePath));
  }

  if (envLines.length > 0) {
    const header = envContent ? "" : "# Generated by VibeGuard. Do not commit this file.\n";
    const prefix = envContent && !envContent.endsWith("\n") ? "\n" : "";
    writeTextFile(envPath, envContent + prefix + header + envLines.join("\n") + "\n");
  }

  const applied = [];
  if (envLines.length > 0) applied.push(`Moved ${envLines.length} secret value(s) into .env.vibeguard.local.`);
  if (changedFiles.length > 0) applied.push(`Replaced hard-coded secret reads in: ${changedFiles.join(", ")}.`);
  return applied;
}

function parseEnvNames(content) {
  const names = new Set();
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || !trimmed.includes("=")) continue;
    names.add(trimmed.split("=")[0].trim());
  }
  return names;
}

function nextAvailableEnvName(baseName, usedEnvNames) {
  let name = baseName || "VIBEGUARD_SECRET";
  let index = 2;
  while (usedEnvNames.has(name)) {
    name = `${baseName}_${index}`;
    index += 1;
  }
  return name;
}

function unquote(value) {
  if (value.length < 2) return "";
  const first = value[0];
  const last = value[value.length - 1];
  if ((first !== "\"" && first !== "'" && first !== "`") || first !== last) return "";
  return value.slice(1, -1);
}

function replacementFor(language, envName) {
  if (language === "python") return `os.getenv("${envName}", "")`;
  return `process.env.${envName} || ""`;
}

function formatEnvValue(value) {
  if (/^[A-Za-z0-9_./:@+=-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function ensurePythonOsImport(content) {
  if (/^\s*import\s+os\b/m.test(content) || /^\s*from\s+os\s+import\b/m.test(content)) return content;

  const lines = content.split(/\r?\n/);
  let insertAt = 0;
  if (lines[0]?.startsWith("#!")) insertAt = 1;
  if (/^#.*coding[:=]/.test(lines[insertAt] ?? "")) insertAt += 1;
  lines.splice(insertAt, 0, "import os");
  return lines.join("\n");
}
